import com.google.gson.Gson;

import java.io.BufferedReader;
import java.io.IOException;
import java.nio.file.FileSystems;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Random;


/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    private static Quote[] quotes;

    public static void main(String[] args) {

        BufferedReader br = null;
        Path inputPath = FileSystems.getDefault().getPath("assets/recentquotes.json");

        try {
            br = Files.newBufferedReader(inputPath);
        } catch (IOException e) {
            e.printStackTrace();
        }

        Gson gson = new Gson();
        quotes = gson.fromJson(br, Quote[].class);
        System.out.println();

       System.out.println(getRandomQuote());
    }

    protected static String getRandomQuote() {
        Random r = new Random();
        return quotes[r.nextInt(quotes.length)].toAuthorAndTextString();
    }
}
