import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;

import java.io.*;
import java.lang.reflect.Type;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;
import java.nio.file.FileSystems;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Random;


/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {


    public static void main(String[] args) throws IOException {
        try {
            WebQuoteGetter ronSwansonQuote = new WebQuoteGetter();
            FileSystemQuoteGetter fileQuote = new FileSystemQuoteGetter("assets/recentquotes.json");
            fileQuote.addFileSystemQuote(ronSwansonQuote.getRonQuote());
            fileQuote.saveQuotes();
            System.out.println(ronSwansonQuote.getRonQuote());
        } catch (IOException e) {
            // If no internet, will print random quote from file.
            FileSystemQuoteGetter fileQuote = new FileSystemQuoteGetter("assets/recentquotes.json");
            System.out.println(fileQuote.getRandomQuote());
        }

    }


}
